import type { NextPage } from 'next'
import Head from 'next/head'

const Checkout: NextPage = () => {
  async function handleClick() {
    console.log('yo')
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>yooo</h1>
        <button onClick={handleClick}>Heyo</button>

        <p>testing 123</p>
      </main>

      <footer>footer</footer>
    </div>
  )
}

export default Checkout
