import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import useSWR from "swr";
import { fetchPostJSON } from "../utils/api-helpers";

const Home: NextPage = () => {
  const [shouldFetch, setShouldFetch] = useState(false);
  const [data, setData] = useState(false);
  const [stripeUrl, setStripeUrl] = useState("");
  const [btcpayUrl, setBtcPayUrl] = useState("");

  async function handleClick() {
    // setShouldFetch(true);
    // const { data, error } = useSWR(shouldFetch ? "/api/invoice" : null, fetchGetJSON);
    // const res = await fetchGetJSON("/api/invoice");
    const amount = 100.0;
    try {
      const stripe = await fetchPostJSON("/api/stripe_checkout", {
        amount,
      });
      const btcpay = await fetchPostJSON("/api/btcpay", {
        amount,
      });
      console.debug(stripe);
      setStripeUrl(stripe.url);
      setBtcPayUrl(btcpay.checkoutLink);
      console.debug(btcpay);
    } catch (e) {
      console.error(e);
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>yooo</h1>
        <button onClick={handleClick}>Heyo</button>
        {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
        {stripeUrl && <a href={stripeUrl}>Stripe Checkout</a>}
        {btcpayUrl && <a href={btcpayUrl}>BTCPay Checkout</a>}
        <p>testing 123</p>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
